// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GcrCertificateFieldClass", sizeof(GcrCertificateFieldClass), alignof(GcrCertificateFieldClass));
    printf("%s;%zu;%zu\n", "GcrCertificateIface", sizeof(GcrCertificateIface), alignof(GcrCertificateIface));
    printf("%s;%zu;%zu\n", "GcrCertificateSectionClass", sizeof(GcrCertificateSectionClass), alignof(GcrCertificateSectionClass));
    printf("%s;%zu;%zu\n", "GcrCertificateSectionFlags", sizeof(GcrCertificateSectionFlags), alignof(GcrCertificateSectionFlags));
    printf("%s;%zu;%zu\n", "GcrSimpleCertificate", sizeof(GcrSimpleCertificate), alignof(GcrSimpleCertificate));
    printf("%s;%zu;%zu\n", "GcrSimpleCertificateClass", sizeof(GcrSimpleCertificateClass), alignof(GcrSimpleCertificateClass));
    return 0;
}
