on:
  push:
    branches: [ main ]
  pull_request:
name: Build
jobs:
  testing:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/andyholmes/flatter/gnome:47
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        uses: andyholmes/flatter@main
        with:
          files: build-aux/flatpak/de.capypara.FieldMonitor.json
          run-tests: true
