on:
  push:
    branches: [ main ]
  pull_request:
name: Lint
jobs:
  format-check:
    name: Rustfmt Check
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --verbose -- --check

  clippy:
    name: Clippy Checks (Default)
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rust-src

      - name: Run Clippy check
        run: cargo clippy -- -D warnings
